baseURL: "https://arkalim.org"
languageCode: en-us
title: William Ranci Ortigosa
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    # - identifier: blog
    #   name: Blog
    #   url: /blog
    #  weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: experience
      name: Experience
      url: /experience
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50
    - identifier: tags
      name: Tags
      url: /tags
      weight: 60
    # - identifier: notes
    #   name: Notes
    #   url: 
    #   weight: 70

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "William Ranci Ortigosa"
    subtitle: "Hi 👋, I'm William, a current [**Software Engineer Apprentice**](https://www.ibm.com/impact/feature/apprenticeship) at [**IBM**](https://www.ibm.com/us-en?ar=1). I'm a recent dual-enrolled graduate of [**P-Tech Norwalk**](https://ptech.norwalkps.org/) &  [**Norwalk Community College**](https://norwalk.edu/) where I earned an Associate's in Software Engineering and a High School Diploma in the same year. I'm passionate about [**Freelancing**](https://www.upwork.com/), specifically **Ecommerce Web Development**. I'm currently part of the [**Freemote Bootcamp**](https://www.freemote.com/?utm_platform=google&utm_source=12923445580&gc_id=12923445580&h_ad_id=518479656654&gclid=EAIaIQobChMI6fCkkerq_QIVVG1vBB19cgYbEAAYASAAEgKzIfD_BwE) to help me pursue these passions. "
    imageUrl: "home/me.jpg"
    imageWidth: 220
    imageHeight: 220
    # buttons:
    #   - name: Resume
    #     url: ""

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    # - name: "email"
    #   url: "mailto:"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/william-ranci-ortigosa-4b51941ba"
    - name: "github"
      url: "https://github.com/William-Ranci-Ortigosa"
    - name: "youtube"
      url: "https://www.youtube.com/@williamRanci"
    # - name: "cv"
    # url: ""

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
